#!/bin/bash

DIR="`dirname \"$0\"`"
DIRECTORY="$DIR/httpd"
DOCKER_REPOSITORY="dr.cohorte.tech/httpd"
DOCKER_TAG="2.4.51"
DOCKER_USER=$1
DOCKER_PASSWORD=$2
echo "DOCKER_TAG=$DOCKER_TAG"
echo "DOCKER_REPOSITORY=$DOCKER_REPOSITORY"
echo "DOCKER_PASSWORD=$DOCKER_PASSWORD"
echo "DOCKER_REGISTRY=$DOCKER_REGISTRY"
echo "DOCKER_USER=$DOCKER_USER"
echo -e "\x1B[1;32m[INFO] Building Image [$DOCKER_REPOSITORY:$DOCKER_TAG] located on [$DIRECTORY]\x1B[0m"

DIR="`dirname \"$0\"`"
bash $DIR/build_image.sh "$DIRECTORY" "$DOCKER_REPOSITORY" "$DOCKER_TAG" $DOCKER_USER $DOCKER_PASSWORD dr.cohorte.tech
