#!/bin/sh


echo "Content-type: application/json\n"
wJson="{"
i=0
cd ${volume}
for f in *
do
  feature=$(echo $f | cut -d '.' -f 1)
  state=$(echo $f | cut -d '.' -f 2)
 	if [ "$i" != "0" ];then
  	wJson="$wJson,"
  fi

  wJson="$wJson\"$feature\":\"$state\""

  i=$((i + 1))

done

wJson="$wJson}"
echo $wJson
